num = int(input('Digite um valor : '))
print('---'*10)
print('{} e {:2}  = {}'.format(num,1,num*1))
print('{} e {}  = {} '.format(num,2,num*2))
print('{} e {} = {}'.format(num,3,num*3))
print('{} e {}  = {}'.format(num,4,num*4))
print('{} e {:2}  = {}'.format(num,5,num*5))
print('{} e {}  = {} '.format(num,6,num*6))
print('{} e {}  = {}'.format(num,7,num*7))
print('{} e {}  = {}'.format(num,8,num*8))
print('{} e {}  = {}'.format(num,9,num*9))
print('{} e {}  = {}'.format(num,10,num*10))
print('---'*10)